feat(viz): add ability to insert branch steps
KaotoIO/kaoto-ui pull request #1140
Opened 2023-01-20 12:02 UTC by kahboom

This PR adds the ability to insert a step in between two branch steps. Resolves #1114.

## Changes
- Add check in mini catalog to validate inserting branch steps
- Add handling in mini catalog step selection for branch steps
- Enable `insert` edge type for branch steps
- Extract `insertStep` logic into its own testable function
- Improve query params for API request to be more accurate with source/target step
- Improve typings

## Screenshots

![Kapture 2023-01-20 at 11 09 00-2](https://user-images.githubusercontent.com/3844502/213689929-17e5ab23-5657-405e-bbf9-02405a72d51e.gif)

2023-01-20 12:39 UTC, mmelko requested changes
If only one step is left in the branch, I'm not able to add any step into that branch anymore: see: <img width="778" alt="Screenshot 2023-01-20 at 13 37 27" src="https://user-images.githubusercontent.com/6814482/213696750-fe07430d-272f-4c3c-aab7-eb07d5a60a20.png">

2023-01-20 12:58 UTC, kahboom commented
@mmelko but how would you know whether the user wants to add a step to the branch or to the main integration? for this thing I think we would need to have a design review and also be working on building branches visually #786 .

2023-01-20 13:01 UTC, mmelko commented
So the simplest would be to have 2x `+` one in the branch and second at the integration level before the first step of the first step after branches (filter step in this cas)

2023-01-20 13:09 UTC, kahboom commented
I don't see a filter step, but I think I know what you mean. But that's why I mentioned prepend step would need to be supported, and right now it's not. To me that should be in a separate PR.

Actually I'm thinking about it and even if we allowed appending/prepending steps in a branch, it will look really weird to users until we solve #1133 , because it will have two + buttons in between two steps, the user won't know the difference between those buttons, or know that one is to add inside of a branch and the other for outside of the branch.

2023-01-23 12:40 UTC, mmelko approved these changes

2023-01-23 13:11 UTC, merged