fix(step-details): Debounce saveConfig callback
KaotoIO/kaoto-ui pull request #1537
Opened 2023-03-22 15:20 UTC by lordrip

### Context
At the moment of writing, whenever a user writes a character, the saveConfig callback is executed and 2 HTTP calls are triggered to update the YAML integration file.

This becomes problematic for bigger integrations or for long strings because triggers unnecessary server calls.

### Changes
This commit debounces that call by 500ms to leave time for the user to finish writing before updating the YAML file.

[Screencast from 2023-03-22 16-19-58.webm](https://user-images.githubusercontent.com/16512618/226952311-1a3a964e-9aba-467a-9182-9adc1f4cbc04.webm)

fixes https://github.com/KaotoIO/kaoto-ui/issues/1339

2023-03-22 15:49 UTC, igarashitm approved these changes, later dismissed
Aside user testing being done, The code LGTM :+1:

2023-03-22 16:06 UTC, apupier requested changes
the change to the constant of store shoudl be removed. There will be a revert for it for now https://github.com/KaotoIO/kaoto-ui/pull/1538

2023-03-23 08:05 UTC, lordrip commented
> the change to the constant of store shoudl be removed. There will be a revert for it for now #1538

Sure thing, I'll remove it **._.>**

2023-03-23 08:12 UTC, apupier approved these changes

2023-03-23 08:26 UTC, merged