chore: Hide Config tab if no properties exist
KaotoIO/kaoto-ui pull request #1658
Opened 2023-04-17 07:12 UTC by pnaik1

#1271

2023-04-17 09:47 UTC, kahboom requested changes
Tiny nitpick, otherwise this looks good. 👍

2023-04-17 09:47 UTC, kahboom commented on src/components/VisualizationStepViews.tsx
> +    step.parameters?.length?configTabIndex:detailsTabIndex);
Hey @pnaik1 thanks for your contribution! Do you mind to add a space here so it's easier to read? For example like this:
`step.parameters?.length ? configTabIndex : detailsTabIndex);`

2023-04-17 12:17 UTC, pnaik1 commented
yeah sure @kahboom

2023-04-17 13:54 UTC, kahboom commented
@pnaik1 - Thanks for making the change. Unfortunately we don't have a pre-commit hook added yet, maybe I will look at that this week. If you use VSCode, it specifically has an option to apply Prettier only to files changed: https://code.visualstudio.com/updates/v1_49#_only-format-modified-text

Btw, it looks like DeepScan is complaining because it wants you to add `> 0` like this: `{step.parameters?.length > 0 && !hasConfigView && (`. You can see the check [here](https://deepscan.io/dashboard/#view=project&tid=19033&pid=22364&bid=658659&subview=pull-request&prid=1598935). If you don't mind making that quick change I will be happy to merge this.

2023-04-17 17:30 UTC, pnaik1 commented
@kahboom I tried making the changes as asked, but i am getting this error   [ **step.parameters.length' is possibly 'undefined** ]

2023-04-18 08:33 UTC, kahboom approved these changes
thanks so much @pnaik1 !

2023-04-18 08:34 UTC, merged