fix: Add Beans support
KaotoIO/kaoto-ui pull request #1827
Opened 2023-05-22 14:42 UTC by igarashitm

With KaotoIO/kaoto-backend#659, now the `beans` definition pasted in YAML code editor will be preserved.

Fixes: #1721

2023-05-22 14:43 UTC, igarashitm commented on src/store/flowsStore.tsx
> +  (integrationId: string, newStep: IStepProps, options: { mode: 'insert'; index: number }): void;
WebStorm did this behind me, replaced a comma with a semicolon... is this valid?

2023-05-22 15:03 UTC, lordrip requested changes
LGTM I just think that we need to add the missing `metadata` property and we're good to go.

PS: `WebStorm` :broken_heart:

2023-05-22 15:17 UTC, kahboom commented on src/components/SourceCodeEditor.tsx
>    const schemaUri = settings.dsl.validationSchema
@lordrip No real opinion here, just curious why a custom hook over a service?

2023-05-22 15:35 UTC, igarashitm commented on src/components/SettingsModal.tsx
> +    ({ flows, properties, metadata, setFlowsWrapper: setFlows }) => ({
done!

2023-05-22 15:35 UTC, igarashitm commented on src/kogito-integration/KogitoEditorIntegrationProvider.tsx
> +    JSON.parse(JSON.stringify({ flows, properties }))
done!

2023-05-23 07:34 UTC, lordrip approved these changes

2023-05-23 07:34 UTC, merged