add cypress test for 3 step integration
KaotoIO/kaoto-ui pull request #430
Opened 2022-05-24 08:06 UTC by miram13

Which issue(s) this PR fixes: e2e-296

2022-05-24 08:15 UTC, Delawen commented
![unnamed](https://user-images.githubusercontent.com/726590/169983297-3e6c3142-f89a-4539-b275-a5ca6e8888e3.gif)

2022-05-24 08:16 UTC, Delawen approved these changes

2022-05-24 09:00 UTC, kahboom requested changes

2022-05-24 09:00 UTC, kahboom commented on package.json
> +    "@4tw/cypress-drag-drop": "^2.1.0",
This should be a dev dependency instead

2022-05-24 09:00 UTC, kahboom commented on cypress/integration/6-step_integration/step_integration.spec.js
> +});
If you don't mind, please add a line at the end of every file, otherwise you get a little red symbol like this, it's a unix thing.

2022-05-24 12:55 UTC, Delawen commented on cypress.json
>  }
why this new line?

2022-05-24 13:35 UTC, kahboom approved these changes
great job @miram13 !! 🥇

2022-05-24 13:35 UTC, merged

2022-05-24 13:56 UTC, miram13 commented
https://github.com/KaotoIO/kaoto-ui/pull/430#:~:text=You%E2%80%99re%20all%20set,296%2De2e

2022-05-25 06:46 UTC, Delawen commented
Fixes ·#296